openapi: 3.0.3
info: 
  title: WASAPhoto
  description: |- 
    This OpenAPI document describes the APIs required for the Project "WASAPhoto" 
    of the WASA exam of Sapienza University of Rome.
  version: 0.0.1
paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "Maria"
                  pattern: 'ˆ.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: integer
                    example: 1
                    
                    
  /users/{userId}/username:
    put:
      tags: ["user"]
      summary: Set the username of the User
      description: |-
        It sets a new username for the user if the user exists
      operationId: setMyUserName
      parameters:
      - name: userId
        description: Identifier of the user
        in: path
        schema:
          type: integer
          example: 1
        required: true
      requestBody:
        description: New username
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  $ref: "#/components/schemas/User/properties/username"
        required: true
      responses:
        "204":
          description: "Username successfully set"
        "404":
          description: "User not found"
        
      
components:
  schemas:
  
    User:
      description: This object represents a single User of WASAPhoto
      type: object
      properties:
        id:
          description: The unique identifier of the User
          type: integer
          example: 1234
          readOnly: true
        username:
          description: The username of the User
          type: string
          example: "Maria"
          pattern: 'ˆ.*?$'
          minLength: 3
          maxLength: 16
        followers:
          description: List of all users who follow the User
          type: array
          items: 
            $ref: "#/components/schemas/User"
        following:
          description: List of all users followed by the User
          type: array
          items: 
            $ref: "#/components/schemas/User"
        photos:
          description: Stream of Photos uploaded by the User
          type: array
          items: 
            $ref: "#/components/schemas/Photo"
            
    Photo:
      description: This object represents a single Photo that can be uploaded by a User on WASAPhoto
      type: object
      properties:
        id:
          description: The unique identifier of the Photo
          type: integer
          example: 1234
          readOnly: true
        date:
          description: Date that represents when the Photo was uploaded 
          type: string
          format: date-time
          example: "2017-07-21T17:32:28Z"
        likes:
          description: Number of likes that the Photo has
          type: integer
          example: 1
        comments: 
          description: Number of comments that the Photo has
          type: integer
          example: 1
        
      
      
          
          
          
